apiVersion: apps/v1
kind: Deployment
metadata:
  name: crime-deployment
  labels:
    app: crime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crime
  template:
    metadata:
      labels:
        app: crime
    spec:
      containers:
      - name: crime
        image: tomakovv/crime:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: CRIME_RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: configuration
              key: rabbitmq-url
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings

---

apiVersion: v1
kind: Service
metadata:
  name: crime-service
spec:
  type: LoadBalancer
  selector:
    app: crime
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
