version: '3.4'

services:
  crime.api:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: src/CrimeAPI/Dockerfile

  lawenforcement.api:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: src/LawEnforcementAPI/Dockerfile

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=1Secure*Password1
    ports:
        - 1433:1433  
