version: '3.4'

services:

  rep_crime.01.web:
    image: ${DOCKER_REGISTRY-}repcrime01web
    build:
      context: .
      dockerfile: src/REP_CRIME.01.Web/Dockerfile

  crime.api:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: src/CrimeAPI/Dockerfile

  

  #lawenforcement.api:
  #  image: ${DOCKER_REGISTRY-}lawenforcementapi
  #  build:
  #    context: .
  #    dockerfile: src/LawEnforcementAPI/Dockerfile

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo  
  #db:
  #  image: "mcr.microsoft.com/mssql/server:2022-latest"
  #  environment:
  #       - ACCEPT_EULA=Y
  #       - MSSQL_SA_PASSWORD=1Secure*Password1
  #  ports:
  #      - 1433:1433  
  rabbitmq-repcrime: 
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"  
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672" 
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5


