apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawEnforcement-deployment
  labels:
    app: lawEnforcement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lawEnforcement
  template:
    metadata:
      labels:
        app: lawEnforcement
    spec:
      containers:
      - name: lawEnforcement
        image: tomakovv/hospitality_examinations:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: configuration
              key: rabbitmq-url

---

apiVersion: v1
kind: Service
metadata:
  name: lawEnforcement-service
spec:
  type: NodePort
  selector:
    app: crime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010