apiVersion: apps/v1
kind: Deployment
metadata:
  name: law-enforcement-deployment
  labels:
    app: lawEnforcement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: law-enforcement
  template:
    metadata:
      labels:
        app: law-enforcement
    spec:
      containers:
      - name: law-enforcement
        image: tomakovv/law_enforcement:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: configuration
              key: rabbitmq-url
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
---

apiVersion: v1
kind: Service
metadata:
  name: law-enforcement-service
spec:
  type: ClusterIP
  selector:
    app: law-enforcement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
