apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  sql-pass: MVNlY3VyZSZQYXNzd29yZDE=
  mongo-user: bW9uZ291c2Vy
  mongo-pass: bW9uZ29wYXNzd29yZA==
  mongo-connectionstring: bW9uZ29kYjovL21vbmdvdXNlcjptb25nb3Bhc3N3b3JkQG1vbmdvLXNlcnZpY2U6MjcwMTcv
  