// <auto-generated />
using System;
using LawEnforcement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawEnforcement.Persistence.Migrations
{
    [DbContext(typeof(LawEnforcementContext))]
    partial class LawEnforcementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LawEnforcement.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("CrimeEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LawEnforcementTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawEnforcementTeamId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LawEnforcement.Domain.Entities.LawEnforcementTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EnforcementNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LawEnforcementTeams");
                });

            modelBuilder.Entity("LawEnforcement.Domain.Entities.Event", b =>
                {
                    b.HasOne("LawEnforcement.Domain.Entities.LawEnforcementTeam", null)
                        .WithMany("CrimeEvents")
                        .HasForeignKey("LawEnforcementTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LawEnforcement.Domain.Entities.LawEnforcementTeam", b =>
                {
                    b.Navigation("CrimeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
